### ISSUE TITLE
This Issue

### ISSUE THREAD

**Issue by Fawadkhanfk** [Sh1Yo/request_smuggler#1]
warning: build failed, waiting for other jobs to finish...
error: failed to compile `request_smuggler v0.1.0-alpha.1`, intermediate artifacts can be found at `/tmp/cargo-installgMlo6q`

Caused by:
  build failed

**Comment by Sh1Yo** [comment]
Hi, please include that `/tmp/cargo-installgMlo6q` and/or the whole building log.

**Comment by Sh1Yo** [comment]
No additional response was provided
